# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

# Inspired on https://github.com/juliasilge/tidytext
environment:
  global:
    WARNINGS_ARE_ERRORS: 1
    USE_RTOOLS: true

build_script:
  - travis-tool.sh install_r curl
  - travis-tool.sh install_r testthat
  - Rscript scripts/install_r_packages.R
  #- travis-tool.sh install_github Giappo/mbd@v1.0
  #- travis-tool.sh install_github Giappo/mbd.SimTrees@v0.1
  #- travis-tool.sh install_github jimhester/covr
  #- travis-tool.sh install_github jimhester/lintr
  #- travis-tool.sh install_github ropensci/beautier@v2.3.3
  #- travis-tool.sh install_github ropensci/tracerer@v2.0.3
  #- travis-tool.sh install_github ropensci/beastier@v2.1.2
  #- travis-tool.sh install_github ropensci/mauricer@v2.0.6
  #- travis-tool.sh install_github ropensci/babette@v2.1.1
  #- travis-tool.sh install_github richelbilderbeek/mcbette@v1.8
  #- travis-tool.sh install_github thijsjanzen/nLTT@v1.4.3
  #- travis-tool.sh install_github richelbilderbeek/becosys@v1.0.1
  #- travis-tool.sh install_github thijsjanzen/nodeSub@v0.4.2
  #- travis-tool.sh install_github richelbilderbeek/pirouette@v1.6.2
  #- travis-tool.sh install_github richelbilderbeek/peregrine@v1.0
  - travis-tool.sh install_deps
  - Rscript -e "beastier::install_beast2()"

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
