#!/bin/bash
#
# Build razzo as if on CRAN
#
# Usage, locally:
#
# ./build_cran
#
# Usage, on Peregrine:
#
# sbatch build_cran
#
#SBATCH --time=1:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --mem=1G
#SBATCH --job-name=razzo_build_cran
#SBATCH --output=razzo_build_cran.log
module load Pandoc

mkdir build

cp -r ../R build
cp -r ../inst build
cp -r ../man build
cp -r ../src build
cp -r ../vignettes build
cp ../DESCRIPTION build
cp ../LICENSE build
cp ../NAMESPACE build

cd build
R CMD build .
R CMD check --as-cran $(ls *.tar.gz)