# Script to install razzo and its dependencies
devtools::install_github("thijsjanzen/nLTT", ref = "v1.4.3")
devtools::install_github("ropensci/beautier", ref = "v2.3.3")
devtools::install_github("ropensci/tracerer", ref = "v2.0.3")
devtools::install_github("ropensci/beastier", ref = "v2.1.2")
devtools::install_github("ropensci/mauricer", ref = "v2.0.6")
devtools::install_github("ropensci/babette", ref = "v2.1.1")
devtools::install_github("richelbilderbeek/mcbette", ref = "v1.8")
devtools::install_github("thijsjanzen/nodeSub", ref = "v0.4.2")
devtools::install_github("richelbilderbeek/pirouette", ref = "v1.6.2")
devtools::install_github("Giappo/mbd", ref = "v1.0")
devtools::install_github("Giappo/mbd.SimTrees", ref = "v0.1")
devtools::install_github("richelbilderbeek/becosys", ref = "v1.0.1")
devtools::install_github("richelbilderbeek/peregrine", ref = "v1.0")

