# Script to install razzo and its dependencies
devtools::install_github("ropensci/beautier")
devtools::install_github("ropensci/tracerer")
devtools::install_github("ropensci/beastier")
devtools::install_github("ropensci/mauricer")
devtools::install_github("ropensci/babette")
devtools::install_github("richelbilderbeek/mcbette")
devtools::install_github("richelbilderbeek/pirouette", ref = "richel")
devtools::install_github("richelbilderbeek/peregrine")
devtools::install_github("richelbilderbeek/razzo", ref = "richel")
