# mbd_ML_cluster0----------------
#' @author Giovanni Laudanno
#' @title Maximization of the loglikelihood under a multiple birth-death diversification model, wrapped for cluster usage.
#' @description mbd_ML_cluster0 computes the maximum likelihood estimates of the parameters of a multiple birth-death diversification model. Differently from mbd_ML it needs only the number "s" of the simulations, making it suitable to run on a cluster. You will need two files to make it work: "general_settings","sim_data"; they are both generated by mbd_sim_dataset0.
#' @inheritParams default_params_doc
#' @param s The number of the simulation you want to evaluate.
#' @param initparsopt The initial values of the parameters that must be optimized
#' @param idparsopt The ids of the parameters that must be optimized.
#'   The ids are defined as follows:
#' \itemize{
#' \item id == 1 corresponds to lambda (multiple speciation trigger rate)
#' \item id == 2 corresponds to mu (extinction rate)
#' \item id == 3 corresponds to q (single-lineage speciation probability)
#' }
#' @param parsfix The values of the parameters that should not be optimized.
#' @return The output is saved on the document "mbd_MLE.txt".
#' \itemize{
#' \item First column contains ML estimates for lambda.
#' \item Second column contains ML estimates for mu.
#' \item Third column contains ML estimates for lambda.
#' \item Fourth column contains maximum likelihood.
#' \item Fifth column contains the number of additional species coming from multiple births in the evaluated tree.
#' }
#'
#' @examples
#' # You will need two files to make it work: "general_settings","sim_data".
#' # mbd:::mbd_ML_cluster0(1)
#'
#' @export
mbd_ML_cluster0 <- function(
  s,
  initparsopt = c(1.8, 0.3, 0.15)
){
  # initparsopt=c(1.8,0.3,0.15);
  parnames <- c("lambda","mu","nu","q")
  n_pars <- length(parnames)
  idparsopt <- 1:n_pars
  parsfix <- NULL

  # simpath=paste("sims/",sim_pars[1],"-",sim_pars[2],"-",sim_pars[3],"/",sep = '')
  simpath = getwd()

  datapath <- paste(simpath, "/data",sep = '')
  load(file = paste(datapath, "/general_settings",sep = ''))
  load(file = paste(datapath, "/sim_data",sep = ''))
  print(s)

  if ( !file.exists(paste(simpath,"/errors",sep = '')) ){dir.create(paste(simpath,"/errors",sep = ''))}
  sink(file = paste(simpath,"/errors/mbd_MLE_errors",s,".txt",sep = ''), append = T)

  res <- mbd:::mbd_ML0(
    brts = sim_data[[s]],
    initparsopt = initparsopt,
    idparsopt=idparsopt,
    idparsfix = (1:n_pars)[-idparsopt],
    parsfix = parsfix,
    missnumspec = 0,
    cond = cond,
    soc = soc,
    tips_interval = tips_interval,
    res = 10*(1+length(brts)+missnumspec),
    tol = c(1E-3, 1E-4, 1E-6),
    maxiter = 1000 * round((1.25)^length(idparsopt)),
    changeloglikifnoconv = FALSE,
    optimmethod = 'subplex'
  )

  #additional tree info
  how_many_multiple=percent_multiple <- -1;
  if (length(sim_data[[s]]) > 2){
    test0 <- sim_data[[s]][-1]; #actual branching events
    test1 <- duplicated( test0 ); #additional species
    test2 <- test1
    for (iii in 2:length(test1)) {
      if(test1[iii] == TRUE) {
        test2[iii - 1] <- TRUE
      }
    } #considering also the first species at each multiple event
    how_many_multiple=sum(test2);
    percent_multiple <- how_many_multiple/length(test2);
  }
  # additional_species = sum( duplicated(sim_data[[s]]) );
  tips <- length(sim_data[[s]])+1;

  out <- c(res[1:(n_pars+1)],how_many_multiple,tips,percent_multiple,s);
  out2 <- out;#names(out2)=c("lambda","mu","q","LL","species born from multiple events","number of tips","percentage of species born from multiple events","tree id")
  names(out2)=c(parnames,"LL","species born from multiple events","number of tips","percentage of species born from multiple events","tree id")
  print(out2)
  #out[1] = lambda
  #out[2] = mu
  #out[3] = q
  #out[4] = LL
  #out[5] = species born from multiple events
  #out[6] = number of tips
  #out[7] = percentage of species born from multiple events
  #out[8] = tree id
  sink()
  print(out2)

  utils::write.table(
    matrix(
      out,
      ncol = length(out)
    ),
    file = paste(simpath,"/mbd_MLE",s,".txt",sep = ''),
    append = TRUE,
    row.names = FALSE,
    col.names = FALSE,
    sep = ","
  )
  if (res[1:4] != c(-1,-1,-1,-1)) {
    suppressWarnings(
      file.remove(
        paste(simpath,"/errors/mbd_MLE_errors",s,".txt",sep = '')
      )
    )
  }
}
